tasks:
  - name: Install dependencies
    command: |
      cd bouncing-countries-backend
      npm install
      cd ../bouncing-countries
      npm install

  - name: Start backend
    command: |
      cd bouncing-countries
      npm start

  - name: Start frontend
    command: |
      cd bouncing-countries
      npm start


# tasks:
#   - init: npm install && npm run build
#     command: npm run start