tasks:
  - name: Install dependencies
    command: |
      cd bouncing-countries-backend
      npm install
      cd ../bouncing-countries-frontend
      npm install

  - name: Start backend
    command: |
      cd bouncing-countries-backend
      npm start

  - name: Start frontend
    command: |
      cd bouncing-countries-frontend
      npm start